(role/dnscache) update dns forwarder ip
lsst-it/lsst-control pull request #1029
Opened 2024-01-10 13:05 UTC by dtapiacl

This PR is to update the DNS forwarder from Crux to DC-LS-2.

2024-01-10 15:30 UTC, jhoblitt requested changes

2024-01-10 15:30 UTC, jhoblitt commented on hieradata/role/dnscache.yaml
> +  "135.229.139.in-addr.arpa":
I don't think 139.229.135/24 is correct.

2024-01-10 19:44 UTC, jhoblitt commented on hieradata/role/dnscache.yaml
> +  "135.229.139.in-addr.arpa":
I still think the reverse zone is incorrect.

2024-01-10 19:45 UTC, jhoblitt requested changes
Please fix the reverse zone.

2024-01-11 16:27 UTC, jhoblitt commented on hieradata/role/dnscache.yaml
> +  "58.135.229.139.in-addr.arpa":
This is still incorrect.  139.229.135/24 has IT chile servers in it.  We can not delegate this subnet to the PMO.

2024-01-11 16:28 UTC, jhoblitt requested changes
Please delegate the correct subnet.

2024-05-24 19:47 UTC, csilva-cl commented on hieradata/role/dnscache.yaml
> +  "58.135.229.139.in-addr.arpa":
I created the pmo records in r53. The delegation can be removed.

2024-05-28 15:54 UTC, jhoblitt approved these changes
Looks reasonable.

2024-05-28 16:15 UTC, merged