(it-ztp.ls.lsst.org) EL9 Redeployment.
lsst-it/lsst-control pull request #1066
Opened 2024-02-22 16:28 UTC by dtapiacl

IHS-4998

2024-02-22 23:12 UTC, jhoblitt commented on hieradata/node/it-ztp.ls.lsst.org.yaml
> +        dns: "139.229.135.53;139.229.135.54;"
We should set all 3 forward resolvers.

2024-02-22 23:13 UTC, jhoblitt requested changes
Can we rename this host to just `ztp`?

2024-02-23 15:35 UTC, dtapiacl commented on hieradata/node/it-ztp.ls.lsst.org.yaml
> +        dns: "139.229.135.53;139.229.135.54;"
Included missing resolver.

2024-02-23 15:36 UTC, dtapiacl commented
> Can we rename this host to just `ztp`?

I don't see why not, host was renamed to ztp.ls.lsst.org.

2024-02-26 16:14 UTC, jhoblitt approved these changes
LGTM.  Thank you for changing the hostname.

2024-02-26 16:17 UTC, merged