(role/fiberspec) add dco class to fiberspec role
lsst-it/lsst-control pull request #1138
Opened 2024-05-02 16:52 UTC by dtapiacl

2024-05-02 16:54 UTC, jhoblitt requested changes
Please add spec coverage.

2024-05-02 18:18 UTC, dtapiacl commented
> Please add spec coverage.

Thanks for the feedback i would appreciate your review once more.

2024-05-06 21:55 UTC, jhoblitt commented on spec/classes/core/fiberspec_spec.rb
> +      it { is_expected.to contain_class('profile::ts::dco') }
It looks like there are more examples of testing the catalog for a `profile::...` class than I thought there were.  Generally, within a puppet module the goal is test the the resources that end up in catalog and not being sensitive to the internal construction of the module (classes, defines, etc.). The same rule applies for the profiles within our site module.  There are exceptions to the general rule but this case probably shouldn't be an exception.  

Note that as the `fiberspec` example group is being include 2 lines down so this spec test would also be a duplicate.

2024-05-06 21:58 UTC, jhoblitt commented on spec/support/spec/fiberspec.rb
> +    is_expected.to contain_class('profile::ts::dco')
The `support/spec/*` shared examples have be used to test the functionality essentially within a single profile.  They certainly could be used for a role but we haven't been doing that as I think it wouldn't compose very well.  I don't think this shared example should test for "dco" resources in the catalog.

2024-05-06 22:00 UTC, jhoblitt commented on site/profile/manifests/core/fiberspec.pp
> +  include profile::ts::dco
This is duplicating the class inclusion in the role.  While we do sometimes include profile classes from profile classes there isn't a compelling reason to do so here.

2024-05-06 22:05 UTC, jhoblitt commented on hieradata/role/fiberspec.yaml
>  classes:
It appears that I messed when reviewing https://github.com/lsst-it/lsst-control/pull/1134 as there is not a spec file covering this role (there is an auto-magic catchall role test for that cases but it isn't really enough coverage).

Please add a `spec/hosts/roles/fiberspec_spec.yaml`.  Within that file, please include the `dco` shared example group. E.g. `include_examples 'dco'`

2024-05-06 22:05 UTC, jhoblitt requested changes
It appears that I messed when reviewing https://github.com/lsst-it/lsst-control/pull/1134 as there is not a spec file covering this role (there is an auto-magic catchall role test for that cases but it isn't really enough coverage).

Please add a `spec/hosts/roles/fiberspec_spec.yaml`.  Within that file, please include the `dco` shared example group. E.g. `include_examples 'dco'`

2024-05-17 20:20 UTC, jhoblitt requested changes

2024-05-17 20:20 UTC, jhoblitt commented on spec/hosts/roles/fiberspec_spec.rb
> +          include_examples 'dco'
I think we also want `include_examples 'fiberspec` here.

2024-05-21 21:30 UTC, jhoblitt approved these changes

2024-05-23 13:55 UTC, merged