(site/ls) bump rke to 1.5.8
lsst-it/lsst-control pull request #1154
Opened 2024-05-15 00:34 UTC by cbarria

Bump the rke client to version 1.5.8 to entire LS

2024-05-15 15:30 UTC, jhoblitt requested changes
The rke version can also be removed form `cluster/antu/role/rke.yaml`.

2024-05-15 18:36 UTC, jhoblitt approved these changes
LGTM.

2024-05-15 23:07 UTC, dtapiacl commented on spec/hosts/nodes/gaw01.ls.lsst.org_spec.rb
Question ?: How was the new checksum generated ? @cbarria

2024-05-15 23:07 UTC, dtapiacl approved these changes
LGTM.

2024-05-16 13:00 UTC, cbarria commented on spec/hosts/nodes/gaw01.ls.lsst.org_spec.rb
if you go to the project page on github, there is a sha256 checksum file in the lower part
https://github.com/rancher/rke/releases/tag/v1.5.8

2024-05-16 13:14 UTC, merged