(node/lsstcam-vw01.cp.lsst.org) Provision EL9 host
lsst-it/lsst-control pull request #1156
Opened 2024-05-16 14:27 UTC by igonzalezcl

2024-05-16 14:35 UTC, dtapiacl requested changes, later dismissed
Please double check tests for the correct names.

2024-05-16 14:35 UTC, dtapiacl commented on spec/hosts/nodes/lsstcam-vw01.cp.lsst.org_spec.rb
Please update the hostname on the test to the correct value.

2024-05-17 20:58 UTC, jhoblitt commented on hieradata/node/lsstcam-vw01.cp.lsst.org.yaml
It looks like this host doesn't have a device in ipam.  It would be great if we could correct issues like that when reprovisioning a host.

2024-05-30 00:28 UTC, jhoblitt requested changes
Please squash 8b14f6ab482dc245278929806ba13a5aa3cdcfd8

2024-06-18 17:07 UTC, jhoblitt approved these changes
LGTM. Thank you for updating ipam.

2024-06-25 17:19 UTC, merged