(node/lsstcam-fb01.cp.lsst.org) deploy host as el9
lsst-it/lsst-control pull request #1169
Opened 2024-05-23 00:51 UTC by dtapiacl

2024-05-23 01:00 UTC, dtapiacl commented
This host behaves the same way as lsstcam-fcs as it uses canbus and will have to be deployed as EL7.

2024-05-23 16:13 UTC, glennmorris commented
Added a couple of commits to enable the ccs canbus module.
The Puppetfile bump will lead to a trivial merge conflict at some point, sorry.
It requires a private hiera change too.

2024-05-23 16:44 UTC, glennmorris approved these changes

2024-05-30 00:13 UTC, jhoblitt requested changes
This device is missing from ipam.

2024-05-30 00:13 UTC, jhoblitt commented on hieradata/node/lsstcam-fb01.cp.lsst.org.yaml
> +    ipaddress: "139.229.175.89"
This address is missing from ipam.

2024-06-11 17:46 UTC, jhoblitt approved these changes

2024-06-11 21:08 UTC, merged