(node/lsstcam-vw02.cp.lsst.org) provision host EL9
lsst-it/lsst-control pull request #1179
Opened 2024-05-29 19:11 UTC by badenerb

2024-05-29 19:37 UTC, dtapiacl submitted a review, later dismissed
Please bind this host to a device on IPAM.

2024-05-30 00:32 UTC, jhoblitt requested changes

2024-05-30 00:32 UTC, jhoblitt commented on spec/hosts/nodes/lsstcam-vw02.cp.lsst.org_spec.rb
> +    next if os =~ %r{centos-7-x86_64}
```suggestion
    next unless os =~ %r{almalinux-9-x86_64}
```

2024-05-30 00:33 UTC, jhoblitt requested changes
Please squash or improve the commit title of 06abd3d894fb4e7ca7dc7f2a901b403f034df34c

2024-06-11 19:23 UTC, jhoblitt approved these changes
LGTM.

2024-06-11 20:16 UTC, badenerb commented
> Please bind this host to a device on IPAM.

Fixed this

2024-06-11 20:17 UTC, badenerb commented
> Please bind this host to a device on IPAM.

Fixed

2024-06-11 20:28 UTC, merged