(node/foreman.cp) elqui dhcp pools for vlan1801 and vlan1802
lsst-it/lsst-control pull request #1219
Opened 2024-06-11 18:01 UTC by julioconstanzo

Add DHCP pool configs for VLAN1801 and VLAN1802

2024-06-11 18:25 UTC, jhoblitt requested changes

2024-06-11 18:25 UTC, jhoblitt commented on hieradata/node/foreman.cp.lsst.org.yaml
> +      - "139.229.181.1 139.229.181.20"
The "range" is the set of IPs used for dynamic leases.  The "dhcp reservations" we create from foreman can be within that range but it can cause problems as the dhcp server will happily hand out the reservation address to random dhcp requests.  Thus, we want the range to be small and not overlap with the address space we will use for reservations.  The way isc dhcpd handles this is confusing.

The range should be shrunk down to be only a few IPs.

2024-06-11 18:25 UTC, jhoblitt commented on hieradata/node/foreman.cp.lsst.org.yaml
> +      - "139.229.181.33 139.229.181.52"
Similar to ELQUI, the range should be shrunk down to be only a few IPs.

2024-06-12 14:09 UTC, julioconstanzo commented
dynamic dhcp ranges were modified

2024-06-12 15:15 UTC, dtapiacl approved these changes
LGTM.

2024-06-12 20:58 UTC, jhoblitt approved these changes
LGTM.

2024-06-12 21:12 UTC, merged