(Puppet) Remove sysstat package from hosts.
lsst-it/lsst-control pull request #1248
Opened 2024-07-01 19:47 UTC by dtapiacl

To address the high CPU usage on some nodes making hosts unresponsive, it was decided to remove the sysstat package from our hosts.

Ticket of reference: https://rubinobs.atlassian.net/browse/IT-5490

Crontab will have to be cleaned up manually.

2024-07-02 16:11 UTC, jhoblitt reviewed
The plan is to cleanup the crontab of > 300 hosts manually?

2024-07-02 18:12 UTC, dtapiacl commented
> The plan is to cleanup the crontab of > 300 hosts manually?

Probably not of course, i did not find on our gitrepo the cronjob that manages the sysstat cron. If you could point as to what the best approach would be I would appreciate it.

2024-07-05 23:05 UTC, jhoblitt requested changes, later dismissed
Per discussion, cleanup the sysstat package needs to be implemented.

2024-07-17 17:18 UTC, csilva-cl approved these changes
looks good

2024-07-17 17:25 UTC, merged