(node/auxtel-hcu01.cp.lsst.org) add el9 network and tests
lsst-it/lsst-control pull request #1481
Opened 2024-09-27 15:36 UTC by dtapiacl

Converting auxtel devices to EL9.

2024-09-27 16:09 UTC, gseriche approved these changes

2024-09-27 16:13 UTC, jhoblitt requested changes

2024-09-27 16:13 UTC, jhoblitt commented on hieradata/node/auxtel-hcu01.cp.lsst.org.yaml
> +        uuid: "df30450e-88e5-40c5-bdc8-0edf49cd7e3e"
duplicate uuid

2024-09-27 16:13 UTC, jhoblitt commented on spec/hosts/nodes/auxtel-hcu01.cp.lsst.org_spec.rb
> +        it { expect(nm_keyfile['ipv6']['method']).to eq('disabled') }
This duplicates one of the examples in `nm disabled interface`.

2024-09-27 16:13 UTC, jhoblitt commented on spec/hosts/nodes/auxtel-hcu01.cp.lsst.org_spec.rb
> +        it { expect(nm_keyfile['ipv6']['method']).to eq('disabled') }
This duplicates one of the examples in `nm disabled interface`.

2024-09-27 16:13 UTC, jhoblitt commented on spec/hosts/nodes/auxtel-hcu01.cp.lsst.org_spec.rb
> +      context 'with enp8s0' do
Two disabled interfaces listed out is OK but if it was any more I'd have preferred to see an array iterated over to keep it DRY.

2024-09-27 16:15 UTC, jhoblitt commented
Something to be aware of is that interfaces named "in the bios". E.g. eno1, em1, etc. will be stable when upgrading to EL9 but the automagically named interfaces will change.

2024-09-30 16:04 UTC, jhoblitt approved these changes

2024-11-29 01:26 UTC, closed without merging