(node/comcam-archiver.cp) add EL9 network configuration & tests
lsst-it/lsst-control pull request #1483
Opened 2024-09-30 20:09 UTC by dtapiacl

2024-09-30 20:47 UTC, jhoblitt requested changes
This looks good but as we are revisiting the network configuration it makes sense to get rid of the dds interface since it hasn't been used for more than a year.

2024-09-30 20:47 UTC, jhoblitt commented on hieradata/node/comcam-archiver.cp.lsst.org.yaml
> +  eno2:  #dds interface
OSPL/DDS no longer runs on the -archiver hosts. I think we should disable the dds interface and free any route53 records.

2024-10-01 13:27 UTC, cbarria approved these changes
had to put `nfs::client_enabled: true` to enable it. Host was re-provision on this branch.

2024-10-01 15:39 UTC, jhoblitt approved these changes

2024-10-01 18:22 UTC, gseriche approved these changes
lgtm

2024-10-02 12:12 UTC, merged